"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/sidebar";
import { useEffect, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }) {

  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const handletoggleSidebar =() => {
    console.log("toggleSidebar");
    setIsSidebarOpen(!isSidebarOpen);
  
  }

  return (
    <html lang="en">
      <body className={`flex gap-[24px]  bg-[#F8F8F8]  ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="">
        <Sidebar
          isSidebarOpen={isSidebarOpen}
        />
       {isSidebarOpen && (
      <div className='bg-black/60 w-full h-full absolute md:hidden'
      onClick={()=> setIsSidebarOpen(false)}
     ></div>
       )  
      }

        </div>
        <div className=" w-[90%] md:w-[95%] md:pl-[220px]">
          <Navbar 
          toggleSidebar={handletoggleSidebar}
          isSidebarOpen={isSidebarOpen}
          />
        {children}
        </div>
      </body>
    </html>
  );
}
